
import React from 'react';
import { Language } from './types';

export const TRANSLATIONS = {
  [Language.EN]: {
    appName: 'StallMate',
    ordering: 'Ordering',
    inventory: 'Inventory',
    analytics: 'Analytics',
    records: 'Records',
    settings: 'Settings',
    total: 'Total',
    checkout: 'Checkout',
    addToCart: 'Add to Cart',
    cash: 'Cash',
    payme: 'PayMe',
    alipay: 'Alipay',
    fps: 'FPS',
    confirmPayment: 'Confirm Payment',
    scanToPay: 'Scan to Pay',
    dailyReport: 'Daily Report',
    profit: 'Profit',
    revenue: 'Revenue',
    stockLevel: 'Stock Level',
    aiScan: 'Smart Scan Inventory',
    uploadPhoto: 'Upload Label/Invoice',
    extracting: 'Extracting Details...',
    noProducts: 'No products in stock.',
    stockOutAlert: 'Stock Low Alert!',
    bestSellers: 'Best Selling Items',
    noRecords: 'No transactions yet.',
    history: 'History',
    driveFolder: 'Drive Folder',
    selectDrive: 'Connect Google Drive',
    cameraRoll: 'Camera Roll',
    priceModified: 'Price Modified',
    stockModified: 'Stock Modified',
    saveChanges: 'Save Changes',
    editProduct: 'Edit Product',
    stockThreshold: 'Stock Alert Threshold',
    telegramSettings: 'Telegram Alert Config',
    botToken: 'Bot Token',
    chatId: 'Chat ID',
    notificationPref: 'Notification Preferences',
    notifNone: 'No Notifications',
    notifTransaction: 'Detailed Transaction Records',
    notifStock: 'Stock Less Than Threshold (Low Stock)',
    notifBoth: 'Both Records & Stock Alerts',
    transactionCount: 'Total Transactions',
    newCustomers: 'New Customers',
    refundCount: 'Total Refunds',
    cashReceived: 'Cash Received',
    changeDue: 'Change Due',
    dailySettlement: 'Daily Settlement',
    settlementTime: 'Auto-Settlement Time',
    enableAutoSettlement: 'Enable Auto Settlement',
    settleNow: 'Settle & Export Now',
    settlementDescription: 'Generate Excel reports automatically at the chosen time.',
    refund: 'Refund',
    refundItems: 'Select Items to Refund',
    refundReason: 'Reason for Refund',
    refundMethod: 'Refund Method',
    processRefund: 'Confirm Refund',
    refunded: 'Refunded',
    partialRefund: 'Partial Refund',
    reasonDamaged: 'Damaged Item',
    reasonCustomer: 'Customer Changed Mind',
    reasonMistake: 'Order Mistake',
    reasonOther: 'Other Reason',
    settlementSkipped: 'No transactions recorded today. Settlement skipped.',
    settlementSuccess: 'Cloud settlement successful',
    settlementFailed: 'Cloud settlement failed',
    settlementOffline: 'Not logged in or offline. Settlement file downloaded locally only.',
    showImages: 'Show Images',
    hideImages: 'Hide Images',
    instagram: 'Instagram Name',
    facebook: 'Facebook Name',
    discount: 'Discount',
    applyDiscount: 'Apply Discount',
    discountType: 'Discount Type',
    percentage: 'Percentage (%)',
    oneTimeOffer: 'One Time Offer',
    targetPrice: 'Target Price',
    applyToAll: 'Apply to All Items',
    applyToSelected: 'Apply to Selected Items',
    originalTotal: 'Original Total',
    discountAmount: 'Discount Amount',
  },
  [Language.ZH]: {
    appName: '攤友',
    ordering: '落order',
    inventory: '搵貨',
    analytics: '生意分析',
    records: '收據',
    settings: '設置',
    total: '總共',
    checkout: '埋單',
    addToCart: '加落車仔',
    cash: '現金',
    payme: 'PayMe',
    alipay: '支付寶',
    fps: '轉數快',
    confirmPayment: '確認收款',
    scanToPay: '掃 Code 畀錢',
    dailyReport: '每日報表',
    profit: '利潤',
    revenue: '營業額',
    stockLevel: '仲有幾多貨',
    aiScan: '智能掃描入庫',
    uploadPhoto: '上傳標籤/發票',
    extracting: '幫緊你幫緊你...',
    noProducts: '賣晒。',
    stockOutAlert: '就黎無貨！',
    bestSellers: '暢銷產品',
    noRecords: '仲未開過單呀~加油啦!',
    history: '改過啲乜 (紀錄)',
    driveFolder: 'Google Drive',
    selectDrive: '連去 Google Drive',
    cameraRoll: '喺相簿搵',
    priceModified: '改咗價錢',
    stockModified: '改咗貨量',
    saveChanges: '儲存更改',
    editProduct: '修改貨品資料',
    stockThreshold: '低過呢個數就叫我',
    telegramSettings: 'Telegram 警報設置',
    botToken: '機器人 Token',
    chatId: '聊天 ID',
    notificationPref: '通知偏好設置',
    notifNone: '關閉通知',
    notifTransaction: '每一筆詳細交易記錄',
    notifStock: '庫存低於預警值 (15% 警報)',
    notifBoth: '交易記錄及庫存警報',
    transactionCount: '交易總數',
    newCustomers: '新客仔',
    refundCount: '退款次數',
    cashReceived: '實收現金',
    changeDue: '找返',
    dailySettlement: '每日結算',
    settlementTime: '自動結算時間',
    enableAutoSettlement: '開返自動結數先',
    settleNow: '即刻埋數',
    settlementDescription: '到咗時間會自動整份 Excel 營業報表畀你。',
    refund: '退錢',
    refundItems: '揀邊件要退目',
    refundReason: '點解要退',
    refundMethod: '點退法',
    processRefund: '確定退款',
    refunded: '退咗錢喇',
    partialRefund: '部分退款',
    reasonDamaged: '件貨爛咗',
    reasonCustomer: '客仔唔想要',
    reasonMistake: '落錯單',
    reasonOther: '其他原因',
    settlementSkipped: '今日冇生意，唔撚使結數。',
    settlementSuccess: '雲端結數搞掂',
    settlementFailed: '雲端結算失敗',
    settlementOffline: '未登入或斷咗線，份報表只係儲喺電話度。',
    showImages: '睇相',
    hideImages: '收埋啲相',
    instagram: 'Instagram 名稱',
    facebook: 'Facebook 名稱',
    discount: '減價',
    applyDiscount: '用折扣',
    discountType: '點樣減',
    percentage: '俾折頭 (%)',
    oneTimeOffer: '一口價',
    targetPrice: '目標價格',
    applyToAll: '全部一齊減',
    applyToSelected: '揀中嗰啲先減',
    originalTotal: '原價總共',
    discountAmount: '減咗',
  }
};

export const PAYMENT_QR_CODES = {
  PAYME: 'https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=PayMe_Mock_Endpoint',
  ALIPAY: 'https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=Alipay_Mock_Endpoint',
  FPS: 'https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=FPS_Mock_Endpoint'
};
